# Generated by Django 5.0.6 on 2024-07-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimage_product_historicalproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
    ]
