# Generated by Django 5.0.6 on 2024-08-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
    ]
