# Generated by Django 5.0.6 on 2024-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_historicalproductreview_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductreview',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
