# Generated by Django 5.0.6 on 2024-09-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_historicalproductreview_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproductreview',
            old_name='messagee',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='messagee',
            new_name='message',
        ),
    ]
