# Generated by Django 5.0.6 on 2024-09-24 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_messagee_historicalproductreview_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Total sales'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Total sales'),
        ),
    ]
