# Generated by Django 5.0.6 on 2024-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_historicalproduct_stock_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Name')),
                ('init_date', models.DateTimeField(verbose_name='Init date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('image', models.ImageField(upload_to='offert_images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Offert',
                'verbose_name_plural': 'Offerts',
            },
        ),
    ]
