# Generated by Django 5.0.6 on 2024-09-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_offert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='image',
            field=models.TextField(max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image_one',
            field=models.TextField(max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image_three',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image_two',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='image',
            field=models.ImageField(upload_to='offert_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_one',
            field=models.ImageField(upload_to='product_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Imagen'),
        ),
    ]
