# Generated by Django 5.0.6 on 2024-10-09 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_image_alter_historicalcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
    ]
