# Generated by Django 5.0.6 on 2024-10-09 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_historicalproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
    ]
