# Generated by Django 5.0.6 on 2024-10-12 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_historicalproduct_views_product_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='likes_product'),
        ),
    ]
