# Generated by Django 5.0.6 on 2024-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='init_date',
            field=models.DateField(verbose_name='Init date'),
        ),
    ]
