# Generated by Django 5.0.6 on 2024-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_historicalproduct_brand_historicalproduct_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Name'),
        ),
    ]
