# Generated by Django 5.0.6 on 2024-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_principalcategory_historicalprincipalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='principal_categories',
            field=models.ManyToManyField(to='products.principalcategory', verbose_name='principal_category_product'),
        ),
    ]
