# Generated by Django 5.0.6 on 2024-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_principal_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
