# Generated by Django 5.0.6 on 2025-01-22 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_historicalproduct_weight_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight'),
        ),
    ]
