# Generated by Django 5.0.6 on 2024-09-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User id')),
                ('user_ci', models.CharField(max_length=255, verbose_name='User ci')),
                ('user_full_name', models.CharField(max_length=255, verbose_name='User full name')),
                ('user_phone', models.CharField(max_length=255, verbose_name='User phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('type', models.CharField(choices=[('s', 'shop'), ('l', 'local')], default='l', max_length=1, verbose_name='Type')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, verbose_name='Product id')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product name')),
                ('product_full_name', models.CharField(max_length=255, verbose_name='Product full name')),
                ('product_phone', models.CharField(max_length=255, verbose_name='Product phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('cant', models.PositiveIntegerField(verbose_name='Cant')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='order_items')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
