# Generated by Django 5.0.6 on 2024-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_full_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_phone',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cost'),
            preserve_default=False,
        ),
    ]
