# Generated by Django 5.0.6 on 2024-09-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_orderitem_options_remove_orderitem_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('c', 'cash'), ('t', 'transfer'), ('b', 'both')], default='c', max_length=1, verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Transfer'),
            preserve_default=False,
        ),
    ]
