# Generated by Django 5.0.6 on 2024-09-28 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_historicalproduct_stock_remove_product_stock_and_more'),
        ('sales', '0004_order_user_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created_order')),
            ],
            options={
                'verbose_name': 'Local order',
                'verbose_name_plural': 'Local orders',
            },
        ),
        migrations.CreateModel(
            name='LocalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(verbose_name='Cant')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='local_order_item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='local_product_item')),
            ],
            options={
                'verbose_name': 'Local order',
                'verbose_name_plural': 'Local orders',
            },
        ),
    ]
