# Generated by Django 5.0.6 on 2024-09-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_order_options_remove_localorderitem_cant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localorderitem',
            options={'verbose_name': 'Local order item', 'verbose_name_plural': 'Local orders items'},
        ),
        migrations.AlterModelOptions(
            name='localorderitemstock',
            options={'verbose_name': 'Local order item stock', 'verbose_name_plural': 'Local orders items stocks'},
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='user_full_name',
        ),
        migrations.RemoveField(
            model_name='localorder',
            name='user_id',
        ),
        migrations.AddField(
            model_name='localorder',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User first name'),
        ),
        migrations.AddField(
            model_name='localorder',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User last name'),
        ),
    ]
