# Generated by Django 5.0.6 on 2024-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_localorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localorderitemstock',
            name='total_price',
        ),
        migrations.AddField(
            model_name='localorder',
            name='state',
            field=models.CharField(choices=[('p', 'processing'), ('c', 'checked')], default='p', max_length=1, verbose_name='State'),
        ),
    ]
