# Generated by Django 5.0.6 on 2024-10-19 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_offert_end_date_alter_offert_init_date'),
        ('sales', '0011_alter_order_user_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('p', 'processing'), ('c', 'checked')], default='p', max_length=1, verbose_name='State')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('delivery', models.BooleanField(default=True, verbose_name='Delivery')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created_order')),
            ],
            options={
                'verbose_name': 'Shop order',
                'verbose_name_plural': 'Shop orders',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(verbose_name='Cant')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shoporder', verbose_name='shop_order_item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='shop_product_item')),
            ],
            options={
                'verbose_name': 'Shop order item',
                'verbose_name_plural': 'Shop orders items',
            },
        ),
    ]
