# Generated by Django 5.0.6 on 2024-10-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_rename_user_create_shoporder_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderitem',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
