# Generated by Django 5.0.6 on 2024-10-20 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_facture_measure_unit_and_more'),
        ('sales', '0014_shoporderitem_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrderItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(verbose_name='Cant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shoporderitem', verbose_name='shop_order_item_stock')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock', verbose_name='shop_stock_item')),
            ],
            options={
                'verbose_name': 'Shop order item stock',
                'verbose_name_plural': 'Shop orders items stocks',
            },
        ),
    ]
