# Generated by Django 5.0.6 on 2024-11-18 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_localorderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localorderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
    ]
