# Generated by Django 5.0.6 on 2025-01-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_localorderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localorder',
            name='address',
            field=models.CharField(blank=True, default='no definido', max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='localorder',
            name='user_ci',
            field=models.CharField(blank=True, default='no definido', max_length=30, null=True, verbose_name='User ci'),
        ),
        migrations.AlterField(
            model_name='localorder',
            name='user_first_name',
            field=models.CharField(blank=True, default='no definido', max_length=70, null=True, verbose_name='User first name'),
        ),
        migrations.AlterField(
            model_name='localorder',
            name='user_last_name',
            field=models.CharField(blank=True, default='no definido', max_length=70, null=True, verbose_name='User last name'),
        ),
        migrations.AlterField(
            model_name='localorder',
            name='user_phone',
            field=models.CharField(blank=True, default='no definido', max_length=30, null=True, verbose_name='User phone'),
        ),
    ]
