# Generated by Django 5.0.6 on 2025-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_localorder_address_alter_localorder_user_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('c', 'efectivo'), ('t', 'transferencia'), ('b', 'ambos')], default='c', max_length=1, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('s', 'tienda'), ('l', 'local')], default='l', max_length=1, verbose_name='Type'),
        ),
    ]
