# Generated by Django 5.0.6 on 2025-01-26 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_order_payment_type_alter_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=30, verbose_name='Stock id')),
                ('stock_name', models.CharField(max_length=120, verbose_name='Stock id')),
                ('stock_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock inversion cost')),
                ('stock_cant_affter', models.PositiveIntegerField(verbose_name='Stock cant affter')),
                ('stock_cant_before', models.PositiveIntegerField(verbose_name='Stock cant before')),
                ('stock_wharehouse_id', models.CharField(max_length=30, verbose_name='Stock wharehouse id')),
                ('stock_wharehouse_name', models.CharField(max_length=120, verbose_name='Stock wharehouse name')),
                ('cant', models.PositiveIntegerField(verbose_name='Cant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.orderitem', verbose_name='order_item_stock')),
            ],
            options={
                'verbose_name': 'Shop order item stock',
                'verbose_name_plural': 'Shop orders items stocks',
            },
        ),
    ]
