# Generated by Django 5.0.6 on 2025-01-26 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stockmovements_type'),
        ('products', '0030_alter_historicalproduct_weight_alter_product_weight'),
        ('sales', '0020_orderitemstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemstock',
            options={'verbose_name': 'Order item stock', 'verbose_name_plural': 'Orders items stocks'},
        ),
        migrations.CreateModel(
            name='ProductShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_cant', models.PositiveIntegerField()),
                ('sold_cant', models.PositiveIntegerField(blank=True, null=True)),
                ('finish_cant', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='item_product_shift_report')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shift_report', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Product shift report',
                'verbose_name_plural': 'Product shift reports',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('create_time_at', models.TimeField(auto_now_add=True, verbose_name='Created time')),
                ('finish_date_at', models.DateField(null=True, verbose_name='Finish date')),
                ('finish_time_at', models.TimeField(null=True, verbose_name='Finish time')),
                ('create_user_pk', models.CharField(default='Indefinido', max_length=200)),
                ('create_user_username', models.CharField(default='Indefinido', max_length=200)),
                ('warehouse', models.ManyToManyField(related_name='warehouse_shift', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
