# Generated by Django 5.0.6 on 2025-01-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_orderitemstock_options_productshiftreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshiftreport',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shift_report', to='sales.shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='finish_date_at',
            field=models.DateField(blank=True, null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='finish_time_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Finish time'),
        ),
    ]
