# Generated by Django 5.0.6 on 2025-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_productshiftreport_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemstock',
            name='product_import',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product import'),
        ),
    ]
