# Generated by Django 5.0.6 on 2025-02-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_orderitemstock_product_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstock',
            name='stock_code',
            field=models.CharField(max_length=70, verbose_name='Stock id'),
        ),
        migrations.AlterField(
            model_name='orderitemstock',
            name='stock_wharehouse_id',
            field=models.CharField(max_length=70, verbose_name='Stock wharehouse id'),
        ),
    ]
