# Generated by Django 5.0.6 on 2024-09-15 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ci',
            field=models.CharField(default=99020212167, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(default=99020212167, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
            preserve_default=False,
        ),
    ]
