# Generated by Django 5.0.6 on 2024-09-20 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser_ci_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='ci',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
        ),
    ]
