# Generated by Django 5.0.6 on 2024-09-21 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_historicaluser_ci_alter_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CI'),
        ),
    ]
