# Generated by Django 5.0.6 on 2025-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_warehouse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Warehouse'),
        ),
    ]
