# Generated by Django 5.0.6 on 2024-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_socialmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo_site', verbose_name='Logo'),
        ),
    ]
