# Generated by Django 5.0.6 on 2024-09-25 02:09

from django.db import migrations, models
from apps.general.models import *



class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_socialmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalheader',
            name='principal_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Principal comment'),
        ),
        migrations.AlterField(
            model_name='principalheader',
            name='secundary_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secundary comment'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='contact_whatsapp',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Contact whatsapp'),
        )
    ]
