# Generated by Django 5.0.6 on 2024-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_principalheader_principal_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalheader',
            name='image',
            field=models.ImageField(default=1, upload_to='image_presentation', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
