# Generated by Django 5.0.6 on 2024-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_principalheader_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalheader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_presentation', verbose_name='Image'),
        ),
    ]
