# Generated by Django 5.0.6 on 2024-10-12 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_principalheader_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Goal')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goal',
            },
        ),
    ]
