# Generated by Django 5.0.6 on 2024-12-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalheader',
            name='principal_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Principal comment'),
        ),
        migrations.AlterField(
            model_name='principalheader',
            name='secundary_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Secundary comment'),
        ),
    ]
