# Generated by Django 5.0.6 on 2024-09-12 00:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_rename_messagee_historicalproductreview_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category Stock',
                'verbose_name_plural': 'Categories Stocks',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='suppliers_images', verbose_name='Image')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Wharehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Wharehouse',
                'verbose_name_plural': 'Wharehouses',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('measure_unit', models.CharField(choices=[('m', 'mililitros'), ('g', 'gramos'), ('u', 'unidades')], default='u', max_length=1, verbose_name='Measure unit')),
                ('expiration_date', models.DateField(verbose_name='Expire date')),
                ('cant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cant')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Inversion Cost')),
                ('categories', models.ManyToManyField(related_name='category_stock', to='inventory.categorystock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='inventory.wharehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'exit'), ('2', 'entrance')], default='2', max_length=7, verbose_name='Type')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('motive', models.CharField(max_length=255, verbose_name='Motive')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cant')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='inventory.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stock_movement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock movement',
                'verbose_name_plural': 'Stocks Movements',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('cant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cant')),
                ('measure_unit', models.CharField(choices=[('m', 'mililitros'), ('g', 'gramos'), ('u', 'unidades')], default='u', max_length=1, verbose_name='Measure unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_facture', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_facture', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
