# Generated by Django 5.0.6 on 2024-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Address'),
        ),
    ]
