# Generated by Django 5.0.6 on 2024-09-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='measure_unit',
            field=models.CharField(choices=[('m', 'milliliters'), ('g', 'grams'), ('u', 'units')], default='u', max_length=1, verbose_name='Measure unit'),
        ),
    ]
