# Generated by Django 5.0.6 on 2024-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_measure_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wharehouse',
            new_name='Warehouse',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
