# Generated by Django 5.0.6 on 2024-09-14 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_wharehouse_warehouse_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
    ]
