# Generated by Django 5.0.6 on 2024-09-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_facture_measure_unit_alter_stock_cant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovements',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockmovements',
            name='movement_type',
            field=models.CharField(choices=[('1', 'simple'), ('2', 'multiple')], default='1', max_length=1, verbose_name='Type Movement'),
        ),
        migrations.AddField(
            model_name='stockmovements',
            name='stock_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_one_movement', to='inventory.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovements',
            name='stock_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_two_movement', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='stockmovements',
            name='type',
            field=models.CharField(choices=[('1', 'exit'), ('2', 'entrance')], default='2', max_length=1, verbose_name='Type'),
        ),
    ]
