# Generated by Django 5.0.6 on 2024-09-21 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_facture_options_remove_facture_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='amount',
        ),
        migrations.AddField(
            model_name='facture',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Inversion cost'),
        ),
    ]
