# Generated by Django 5.0.6 on 2024-11-12 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_facture_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='storage_threshold',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Storage Threshold'),
        ),
    ]
