# Generated by Django 5.0.6 on 2025-01-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stock_storage_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='expiration_date',
        ),
    ]
