# Generated by Django 5.0.6 on 2025-01-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_stock_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ci',
            field=models.CharField(blank=True, null=True, verbose_name='CI'),
        ),
    ]
