# Generated by Django 5.0.6 on 2025-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_supplier_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovements',
            name='type',
            field=models.CharField(choices=[('1', 'salida'), ('2', 'entrada')], default='2', max_length=1, verbose_name='Type'),
        ),
    ]
