# Generated by Django 5.2.8 on 2025-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stockmovements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CI'),
        ),
    ]
